### ISSUE TITLE
Export Props interface

### ISSUE THREAD

**Issue by vdjurdjevic** [sakhnyuk/rc-scrollbars#13]
Hi. Thanks for restoring the project!
Can you rename `Props` interface to something like `ScrollbarProps` and export it so we can extend it from the outside?

**Comment by Tomassito** [comment]
@vdjurdjevic That's a totally valid request. 
@sakhnyuk I can make it part of the https://github.com/sakhnyuk/rc-scrollbars/pull/11 ?

**Comment by vdjurdjevic** [comment]
@Tomassito  That would be great :)

**Comment by sakhnyuk** [comment]
@vdjurdjevic Hi 👋

Sure! I think with ScrollbarProps, we need to export ScrollValues.

Actually, If you want to help with that, you can open a PR. If not, I'll do it in a few days

**Comment by vdjurdjevic** [comment]
Can @Tomassito do it with the existing pull request since it's really a minor change?

**Comment by nnennajohn** [comment]
Could you please add `className` prop to props, in addition to existing style prop? Thanks.

**Comment by vdjurdjevic** [comment]
@nnennajohn @sakhnyuk Actually, we should add all div props, and forward them to the root element.

**Comment by sakhnyuk** [comment]
@vdjurdjevic 
@nnennajohn 
I've done it in 1.1.0
