### ISSUE TITLE
element.scrollIntoView with true option 

### ISSUE THREAD

**Issue by JumpAttacker** [sakhnyuk/rc-scrollbars#14]
When im using element.scrollIntoView(true)
```
foundItem.scrollIntoView({
        block: "center" // or 'start'
        behavior: "smooth"
      });
```

scroll working is not correnctly

reproduce link
https://codesandbox.io/s/react-fiddle-forked-bvesc?file=/src/App.js

**Comment by Tomassito** [comment]
Is this what you want to achieve?
https://codesandbox.io/s/react-fiddle-forked-h8fvx?file=/src/App.js

**Comment by JumpAttacker** [comment]
i dont need only to btm, some times i need to go not to the last element

and i told you about dat
![image](https://user-images.githubusercontent.com/10989729/104693315-7e05af00-571a-11eb-86e0-173bb602042e.png)

i want to use scrollIntoView with options {block: 'center} but if im using it i got dat

**Comment by Tomassito** [comment]
You can scroll into any position you like with Scrollbars.scrollTop(placeYouWantToScrollInto). See the Spring Scrollbars example that also uses rebound for a smoother effect. 
The options you wanted to use are experimental anyway and should not be used.

**Comment by JumpAttacker** [comment]
but you know easy way to get item's position inside scroll? I only know basic: item.height*x, but i have dynamic height on items, so its hard for me to calc all items (i know it possible, but easiest way to use just scrollIntoView)

**Comment by Tomassito** [comment]
Element.offsettop would be my first call. Anyway it's more like stackoverflow question than Scrollbars related.

**Comment by JumpAttacker** [comment]
yes, thanks for help
