### ISSUE TITLE
When zooming out, the default scroolbar is shown

### ISSUE THREAD

**Issue by diegonunes4** [sakhnyuk/rc-scrollbars#15]
Hello, is this possible to fix? You can recreate this issue if you go to the demo page and just zoom out, the default browser scrollbar will appear.

Thanks for restoring the project!

**Comment by Tomassito** [comment]
Hi @diegonunes4 , we could get some resize listeners rolling.
What do you think @sakhnyuk ?

**Comment by sakhnyuk** [comment]
Hello @diegonunes4.
I need to research how depend zoom in/out on `scrollbarWidth`

https://github.com/sakhnyuk/rc-scrollbars/blob/b3ef55a02489b09f7d2741c1960cf3742731a3f3/src/utils/getScrollbarWidth.ts#L27

Could you provide some information?
You are using macOS? What that browser?

Thank you 👌

**Comment by sakhnyuk** [comment]
@diegonunes4 I've published v1.1.1 with the fix. Could you try to test it?

I have tested Chrome and Safari on macOS. Works well.

**Comment by sakhnyuk** [comment]
There works fine as well 👇
https://codesandbox.io/s/rc-scrollbars-test-qjoc6

**Comment by diegonunes4** [comment]
Hello @sakhnyuk, it's working, sorry that I didn't answer you before, just noticed that today! Thank you very much for the fix.
