### ISSUE TITLE
[v1.1.0]: React does not recognize the `disableDefaultStyles` prop on a DOM element

### ISSUE THREAD

**Issue by ApacheEx** [sakhnyuk/rc-scrollbars#16]
Hello, thanks for supporting awesome library.

After upgrading I noticed this error:

![image](https://user-images.githubusercontent.com/1918108/107130349-1683ef00-68d5-11eb-9789-016cda975c92.png)

**Comment by sakhnyuk** [comment]
Hello @ApacheEx 
Thank you for the issue. I am going to fix it.

**Comment by sakhnyuk** [comment]
@ApacheEx I published v1.1.1 to fix that bug. 

I have tested Chrome and Safari on macOS. 

Please re-open this Issue if it doesn't help

**Comment by ApacheEx** [comment]
works like a charm, thanks for hotfix.
