### ISSUE TITLE
Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by Verrok** [sakhnyuk/rc-scrollbars#6]
Hello, I want to use library, but after installing I faced with 
`Module not found: Error: Can't resolve 'react/jsx-runtime' in 'C:\Projects\node_modules\rc-scrollbars\lib\Scrollbars'`

React: 16.13.1

How can I fix it?

**Comment by sakhnyuk** [comment]
@Verrok Thanks for the issue report.
`react/jsx-runtime` - new feature from React 16.14 and 17.0. 
I'll fix that bug in 1.0.1

**Comment by Verrok** [comment]
Thanks a lot!
